### ISSUE TITLE
Keep Selection after Translation in 2D View

### ISSUE THREAD

**Issue by Sebastian-Jung** [thenlevy/ensnano#10]
Hey, thank you for this Software. I have a small feature request:

Selected objects in Nucleotide Selection Mode or DNA Strand Selection Mode lose selection after translation in 2D View (Middle Mouse Button).
It would be nice if the selection stays, as it's done if one selects whole helices.

**Comment by thenlevy** [comment]
Hello, thank you for your feedback.

> Selected objects in Nucleotide Selection Mode or DNA Strand Selection Mode lose selection after translation in 2D View (Middle Mouse Button).

This is actually a bug that I've missed. I've pushed a patch on the `dev` branch. If you are compiling the software from source you can get a fixed version by doing
`git checkout dev`
`git pull`
and recompile the software.

The next released binaries will also have this bug fixed.
For now, I keep the issue open and will close it when these binaries are released

**Comment by Sebastian-Jung** [comment]
Thanks for the fast reply! I will try the dev branch. If you don't mind I will add some more feature requests/bug reports in the following days, mostly to have them noted somewhere. Don't feel pressured to work on them immediately. I really enjoy ensnano and with some additional features it might be a good substitution to cadnano/scadnano.

**Comment by Sebastian-Jung** [comment]
I tested the dev branch and it works as expected, thank you!

**Comment by thenlevy** [comment]
> Thanks for the fast reply! I will try the dev branch. If you don't mind I will add some more feature requests/bug reports in the following days, mostly to have them noted somewhere. Don't feel pressured to work on them immediately. I really enjoy ensnano and with some additional features it might be a good substitution to cadnano/scadnano.

Thank you, this kind of feedback is really useful and appreciated
