### ISSUE TITLE
Cross-over suggestion in same strand

### ISSUE THREAD

**Issue by Sebastian-Jung** [thenlevy/ensnano#11]
Two (independent?) requests:
* ~Using groups (Red and Green) can sometimes be a bit unintuitive. E.g. if I want to quickly create cross-overs between neighboring helices based on cross-over suggestions I would have to create groups every time.~ Moved to #12
* Currently it is no possible to get cross-over suggestions in the same strand (Even if they are on helices in different groups) . This could e.g. be useful for scaffold routing.

**Comment by thenlevy** [comment]
>     * Using groups (Red and Green) can sometimes be a bit unintuitive. E.g. if I want to quickly create crosslinks between neighboring helices based on crosslink suggestions I would have to create groups every time.
I have created a separated issue for that topic, see #12. Maybe we could simply add an option to add cross-over recommendations between any two helices. 

>     * Currently it is no possible to get crosslink suggestions in the same strand (Even if they are on helices in different groups) . This could e.g. be useful for scaffold routing.

This should be easier to fix. We choosed to not show suggestion between nucleotides of the same strand to reduce the noise but there should instead be an option to enable/disable suggestions between nucleotides of the same strand.

**Comment by Sebastian-Jung** [comment]
> This should be easier to fix. We choosed to not show suggestion between nucleotides of the same strand to reduce the noise but there should instead be an option to enable/disable suggestions between nucleotides of the same strand.

That sounds good. In general, I think it might be a good idea to also give the option to show **all** cross link suggestions between **all** helices (Based on current helix rotations) or (in addition to this option or instead) show possible cross links between from/to the helix one has selected/clicked on.

**Comment by thenlevy** [comment]
I've added a set of parameters to make it possible to see cross-over suggestions involving the scaffold or between the nucleotides that are on the same strands.
There is also a option to show cross-over suggestions between all pair of helices, but on large designs it may considerably slow the software

The options are in the "Eddition" tab
![suggestions_parameters](https://user-images.githubusercontent.com/17043790/140723755-48684ef4-eb19-4d20-89fa-370a611a1914.png)
