### ISSUE TITLE
Make strand ends selectable 

### ISSUE THREAD

**Issue by Sebastian-Jung** [thenlevy/ensnano#14]
[Tested in `dev`]
Similar as in *cadnano* it would be nice to have the option to select endpoint nucleotides. This is usefull if one wants to extend the ends of open strands.

**Comment by thenlevy** [comment]
I have just pushed on `dev` patch that makes it possibles to move several domain ends at once. 

To do so one can select domain ends in the nucleotide selection mode, or whole strands in the strand selection mode

https://user-images.githubusercontent.com/17043790/146523300-a769886d-d7f4-42de-8b57-3b745bd06b37.mp4

Let me know if this fits your needs

**Comment by Sebastian-Jung** [comment]
I gave it a quick test and it seems to work just fine! Thanks!
