### ISSUE TITLE
Weird cross-over suggestion

### ISSUE THREAD

**Issue by Sebastian-Jung** [thenlevy/ensnano#16]
[Description]
When two close helices are cut at suggestied possible cross-over position, the 2D and 3D View show cross-overs that are not possible.

[How to reproduce]
* Create two helices 1, 2 in parallel and assign Group R and Group G respectively
* Cut the strands at the position of the suggested cross-over
![image](https://user-images.githubusercontent.com/998789/140051478-5188827f-e407-4de7-8897-175c6718006d.png)
* Suggested crossovers do not make any sense
![image](https://user-images.githubusercontent.com/998789/140065314-8fb0713b-84ea-4a39-9659-9ceef73ab560.png)
One can see that it suggests the connection of a 3' with a 3' end. If the strands wheren't cut at that position, it would be a good suggestion.

**Comment by thenlevy** [comment]
I've pushed a fix in `dev`.

**Comment by Sebastian-Jung** [comment]
The fix seems to fix the initial problem, but setting one (or both) of the crossovers shows the wrong suggestion in 3D again:
![image](https://user-images.githubusercontent.com/998789/140777900-8e1f2ea9-5615-430b-9aa1-b948252860ac.png)

**Comment by thenlevy** [comment]
I've pushed a patch that allow the user to chose whether or not suggestions could involve cross-over ends. By default, in the above examples, suggestions won't be shown
