### ISSUE TITLE
crash under windows 10

### ISSUE THREAD

**Issue by skydig** [thenlevy/ensnano#24]
windows 10, cargo run crash 
active toolchain
stable-x86_64-pc-windows-msvc (default)
rustc 1.56.1 (59eed8a2a 2021-11-01)

thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
    error matching FRAGMENT shader requirements against the pipeline
    unable to filter the texture (ResourceBinding { group: 0, binding: 2 }) by the sampler (ResourceBinding { group: 0, binding: 1 })
    non-filterable float texture

', C:\Users\Administrator\.cargo\registry\src\mirrors.ustc.edu.cn-12df342d903acd47\wgpu-0.11.1\src\backend\direct.rs:2195:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\release\ensnano.exe` (exit code: 101)

**Comment by thenlevy** [comment]
Thanks for the report. I see that the program was compiled with wgpu 0.11.1 which was released recently (2 hours ago as I'm writing this comment)

Each newer version of wgpu is able to detect errors that the previous one couldn't.
I should probably be able to fix it today.

In the meantime, a possible workaround could be to add
```
[patch.crates-io]
wgpu = 0.11.0
```
At the end of the `Cargo.toml` file at the root of the repp

**Comment by thenlevy** [comment]
I have been able to reproduce the crash and fix it for my machine. I've pushed a patch on `dev`
